/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/*
 * Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 * Copyright 2026 Hans Rosenfeld
 */

#ifndef	_SYS_VNIC_H
#define	_SYS_VNIC_H

#include <sys/types.h>
#include <sys/ethernet.h>
#include <sys/param.h>
#include <sys/mac.h>
#include <sys/mac_flow.h>
#include <sys/dld_ioc.h>
#include <inet/ip.h>
#include <inet/ip6.h>

#ifdef	__cplusplus
extern "C" {
#endif

/*
 * Extended diagnostic codes that can be returned by the various
 */
typedef enum {
	VNIC_IOC_DIAG_NONE,
	VNIC_IOC_DIAG_MACADDR_NIC,
	VNIC_IOC_DIAG_MACADDR_INUSE,
	VNIC_IOC_DIAG_MACADDR_INVALID,
	VNIC_IOC_DIAG_MACADDRLEN_INVALID,
	VNIC_IOC_DIAG_MACFACTORYSLOTINVALID,
	VNIC_IOC_DIAG_MACFACTORYSLOTUSED,
	VNIC_IOC_DIAG_MACFACTORYSLOTALLUSED,
	VNIC_IOC_DIAG_MACFACTORYNOTSUP,
	VNIC_IOC_DIAG_MACPREFIX_INVALID,
	VNIC_IOC_DIAG_MACPREFIXLEN_INVALID,
	VNIC_IOC_DIAG_MACMARGIN_INVALID,
	VNIC_IOC_DIAG_NO_HWRINGS,
	VNIC_IOC_DIAG_MACMTU_INVALID
} vnic_ioc_diag_t;

/*
 * Allowed VNIC MAC address types.
 *
 * - VNIC_MAC_ADDR_TYPE_FIXED, VNIC_MAC_ADDR_TYPE_RANDOM:
 *   The MAC address is specified by value by the caller, which
 *   itself can obtain it from the user directly,
 *   or pick it in a random fashion. Which method is used by the
 *   caller is irrelevant to the VNIC driver. However two different
 *   types are provided so that the information can be made available
 *   back to user-space when listing the kernel defined VNICs.
 *
 *   When a VNIC is created, the address in passed through the
 *   vi_mac_addr and vi_mac_len fields of the vnic_ioc_t structure.
 *
 * - VNIC_MAC_ADDR_TYPE_FACTORY: the MAC address is obtained from
 *   one of the MAC factory MAC addresses of the underyling NIC.
 *
 * - VNIC_MAC_ADDR_TYPE_AUTO: the VNIC driver attempts to
 *   obtain the address from one of the factory MAC addresses of
 *   the underlying NIC. If none is available, the specified
 *   MAC address value is used.
 *
 * - VNIC_MAC_ADDR_TYPE_PRIMARY: this is a VNIC based VLAN. The
 *   address for this is the address of the primary MAC client.
 *
 * - VNIC_MAC_ADDR_TYPE_VRID: the MAC address is a virtual router MAC
 *   address for VRRP, generated by user-space based on the
 *   Virtual Router ID and address family.
 */

typedef enum {
	VNIC_MAC_ADDR_TYPE_UNKNOWN = -1,
	VNIC_MAC_ADDR_TYPE_FIXED,
	VNIC_MAC_ADDR_TYPE_RANDOM,
	VNIC_MAC_ADDR_TYPE_FACTORY,
	VNIC_MAC_ADDR_TYPE_AUTO,
	VNIC_MAC_ADDR_TYPE_PRIMARY,
	VNIC_MAC_ADDR_TYPE_VRID
} vnic_mac_addr_type_t;

#if _LONG_LONG_ALIGNMENT == 8 && _LONG_LONG_ALIGNMENT_32 == 4
#pragma pack(4)
#endif

#define	VNIC_IOC_CREATE				VNICIOC(1)
#define	VNIC_IOC_DELETE				VNICIOC(2)
#define	VNIC_IOC_INFO				VNICIOC(3)
#define	VNIC_IOC_MODIFY				VNICIOC(4)

typedef enum {
	VNIC_IOC_FLAGS_ANCHOR = 1 << 0
} vnic_flags_t;

typedef struct vnic_ioc {
	datalink_id_t	vi_vnic_id;
	datalink_id_t	vi_link_id;
	vnic_mac_addr_type_t vi_mac_addr_type;
	uint_t		vi_mac_len;
	uchar_t		vi_mac_addr[MAXMACADDRLEN];
	uint_t		vi_mac_prefix_len;
	int		vi_mac_slot;
	uint16_t	vi_vid;
	boolean_t	vi_force;
	vrid_t		vi_vrid;
	int		vi_af;
	int		vi_status;
	vnic_flags_t	vi_flags;
	vnic_ioc_diag_t	vi_diag;
	mac_resource_props_t vi_resource_props;
} vnic_ioc_t;


#if _LONG_LONG_ALIGNMENT == 8 && _LONG_LONG_ALIGNMENT_32 == 4
#pragma pack()
#endif

#ifdef	__cplusplus
}
#endif

#endif	/* _SYS_VNIC_H */
